# Generated by Django 5.2.1 on 2025-05-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('progress', 'Progress'), ('completed', 'Completed')], default='confirmed', max_length=20),
        ),
    ]
