# Generated by Django 5.2.1 on 2025-05-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
