# Generated by Django 5.2.1 on 2025-05-24 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='assigned_to',
        ),
    ]
