# Generated by Django 5.2.1 on 2025-05-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_superuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
