CREATE DATABASE hotel_db;
USE hotel_db;
-- DROP DATABASE hotel_db;
SELECT * FROM superuser;
-- django auth user;
SELECT * FROM auth_user;
DELETE FROM auth_user WHERE id = 15;
DELETE FROM SUPERUSER WHERE admin_id = 1;
SELECT * FROM staff;
SELECT * FROM staff_type;
SELECT * FROM customer;
SELECT * FROM food_category;
SELECT * FROM menu;
